version: '3'
services:
  php:
    container_name: my_project_php
    hostname: php
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my_project
    volumes:
      - ./app:/var/www/symfony_docker
  nginx:
    container_name: my_project_nginx
    image: nginx:stable-alpine
    networks:
      - my_project
    ports:
      - "8001:80"
    volumes:
      - ./app:/var/www/symfony_docker
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
networks:
  my_project:
    driver: bridge
